#!/bin/zsh

# This file should be used to set up the initial table.

source /etc/sshd_blacklist/settings
source /etc/sshd_blacklist/functions

# First clear out the existing table if it exists
nft table ip $name
nft delete table ip $name

# Set up table.
cat << EOF > $name.nft
#!/usr/sbin/nft -f
# First create the table, so we can flush it, even if it didn't exist before.
table ip $name
flush table ip $name
table ip $name {
    set $name {
        size 65535
        flags dynamic,timeout
    }

    chain permissiondenied {
        type filter hook input priority filter - 10
        policy accept
        ip saddr @$name update @$name { ip saddr timeout 1h }
        ip saddr @$name log prefix "[$name]" group 0 drop
    }
}
EOF

# Then load this file into the running ruleset
chmod 755 ./$name.nft
./$name.nft
# And save it to disk.
./save_sshd_blacklist
